// scratchpad_manager — packaged form of plugins/scratchpad_manager/host.js.
// ESM module exporting the Cordis function-plugin contract the loader
// expects: named `name` / `inject` / `apply` exports, no default export.
// Generated by scripts/package-plugins.mjs from the dynamic host.js source.
import { defineTool } from '@deepseek-ai/dsh-tools'

export const name = 'scratchpad_manager'
export const inject = ['tools']

export function apply(ctx) {
const STATE_FILE = 'state.md'
    const KEY_RE = /^[A-Za-z0-9_\- ]{1,64}$/

    function parseSections(text) {
      const sections = []
      const lines = text.split(/\r?\n/)
      let current = undefined
      for (const line of lines) {
        const head = /^## (.+)$/u.exec(line)
        if (head !== null) {
          current = { key: head[1], body: [] }
          sections.push(current)
        } else if (current !== undefined) {
          current.body.push(line)
        }
      }
      return sections.map((section) => ({
        key: section.key,
        content: section.body.join('\n').replace(/^\n+|\n+$/g, ''),
      }))
    }

    function serialize(sections) {
      const parts = ['# Working State', '<!-- Managed by scratchpad_manager. Do not edit manually. -->', '']
      for (const section of sections) {
        parts.push(`## ${section.key}`)
        if (section.content.length > 0) parts.push(section.content)
        parts.push('')
      }
      return parts.join('\n')
    }

    function render(value) {
      const head = `${value.path} — ${value.action}`
      const lines = [head]
      if (value.changedKey !== undefined) lines.push(`section: ${value.changedKey}`)
      if (value.sectionCount !== undefined) lines.push(`sections: ${value.sectionCount}`)
      if (value.content !== undefined) lines.push('', value.content)
      return lines.join('\n')
    }

    const tool = defineTool({
      name: 'scratchpad_manager',
      description: `Manage the persistent working-memory file ${STATE_FILE} in the session workspace: read it, append to a section, or overwrite a section. Use it to keep hypotheses, TODO lists, and intermediate conclusions outside the conversation history so the harness can compact the history and re-inject only this condensed scratchpad.`,
      parameters: {
        action: {
          type: 'string',
          required: true,
          enum: ['read', 'append', 'overwrite_section'],
          description: 'read: return the scratchpad (or one section). append: add content to a section (creating it if missing). overwrite_section: replace a section entirely.',
        },
        key: { type: 'string', required: true, description: 'Section key (letters, digits, spaces, _ and - only; max 64 chars).' },
        content: { type: 'string', description: 'Content for append / overwrite_section.' },
      },
      output: {
        schema: {
          type: 'object',
          additionalProperties: false,
          properties: {
            path: { type: 'string', required: true },
            action: { type: 'string', required: true, enum: ['read', 'append', 'overwrite_section'] },
            changedKey: { type: 'string' },
            sectionCount: { type: 'integer', required: true },
            content: { type: 'string' },
            exists: { type: 'boolean', required: true },
          },
        },
        render: (_args, value) => [{ type: 'text', text: render(value) }],
      },
      async execute(args, exec) {
        const fs = ctx.get('fs')
        if (fs === undefined) throw new Error('scratchpad_manager: filesystem service unavailable')
        const cwd = exec.agent?.session.header.cwd
        if (cwd === undefined) throw new Error('scratchpad_manager: no session workspace (exec.agent was undefined)')
        if (!KEY_RE.test(args.key)) throw new Error('scratchpad_manager: key may contain only letters, digits, spaces, _ and - (max 64 chars)')
        const action = args.action
        if ((action === 'append' || action === 'overwrite_section') && typeof args.content !== 'string') {
          throw new Error(`scratchpad_manager: content is required for action "${action}"`)
        }

        const target = await fs.resolve(STATE_FILE, { cwd, signal: exec.signal })
        const info = await fs.stat(target, exec.signal)
        const exists = info !== undefined && info.type === 'file'
        let sections = []
        if (exists) {
          const text = await fs.readText(target, exec.signal)
          sections = parseSections(text)
        }

        let changedKey
        let content
        if (action === 'read') {
          const found = sections.find((section) => section.key === args.key)
          content = found !== undefined
            ? found.content
            : exists ? undefined : '(no scratchpad yet — append a section to create state.md)'
          if (content === undefined && exists) content = '(section not found)'
        } else if (action === 'append') {
          changedKey = args.key
          const found = sections.find((section) => section.key === args.key)
          if (found === undefined) {
            sections.push({ key: args.key, content: args.content })
          } else {
            found.content = found.content.length > 0 ? `${found.content}\n\n${args.content}` : args.content
          }
          content = sections.find((section) => section.key === args.key).content
        } else {
          changedKey = args.key
          const found = sections.find((section) => section.key === args.key)
          if (found === undefined) sections.push({ key: args.key, content: args.content })
          else found.content = args.content
          content = args.content
        }

        if (action !== 'read') {
          await fs.writeText(target, serialize(sections))
        }

        return {
          path: target.displayPath,
          action,
          sectionCount: sections.length,
          exists: exists || action !== 'read',
          ...(changedKey !== undefined ? { changedKey } : {}),
          ...(action === 'read' ? { content } : {}),
        }
      },
    })

    ctx.tools.register(tool)
  
}
