#!/usr/bin/env node
// package-plugins.mjs — convert a dynamic Host-half source (host.js) into a
// mountable npm package (index.js + package.json) in the same plugin directory.
//
// The dynamic form uses the sandbox builtins `harness.defineTool` /
// `harness.registerTool` inside a `return { apply(ctx) {...} }` body. The
// package form uses the real loader contract: ESM named exports
// `name` / `inject` / `apply`, registering through `ctx.tools.register`.
// The tool bodies (parameters/output/render/execute) are copied verbatim.
//
// Usage:
//   node scripts/package-plugins.mjs            # all plugins with host.js
//   node scripts/package-plugins.mjs tree_inspector grep_search
import { readFile, writeFile, readdir, mkdir } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = resolve(fileURLToPath(new URL('..', import.meta.url)))
const pluginsDir = join(repoRoot, 'plugins')

// npm package name + whether the plugin registers tools (needs inject ['tools']).
const PLUGIN_META = {
  tree_inspector: { desc: 'Hierarchical index (directory tree or document TOC) with estimated token sizes' },
  grep_search: { desc: 'Targeted regex filter over one file with context lines' },
  chunk_reader: { desc: 'Sliding-window file reader with a hard 100-line cap' },
  scratchpad_manager: { desc: 'Persistent working-memory block-notes (state.md)' },
  semantic_memory: { desc: 'Workspace-scoped lexical memory recall (semantic_memory_recall, memory_add)' },
  subagent_spawner: { desc: 'Disposable fresh-context subagent with a strict word-capped summary' },
  artifact_offloader: { desc: 'Output-virtualization middleware (tools/post-execute waterfall)' },
  ast_analyzer: { desc: 'Lightweight AST / dependency-graph scanner' },
  diagram_renderer: { desc: 'Mermaid / PlantUML rendering, source always retained' },
  test_runner: { desc: 'QA toolset: run_tests, coverage_analyzer, run_linter' },
  visual_capture: { desc: 'Designer toolset: visual_capture, design_tokens_parser, a11y_validator' },
}

function convertHostSource(source) {
  // Extract the `return { apply(ctx) { ... } }` expression, then unwrap it to
  // the INNER body of apply so the package can re-declare `export function
  // apply(ctx)` without duplication.
  const trimmed = source.trim()
  const open = trimmed.indexOf('return {')
  if (open === -1) throw new Error('host.js must contain a top-level `return {` expression')
  const close = trimmed.lastIndexOf('}')
  if (close <= open) throw new Error('host.js has no closing brace')
  let body = trimmed.slice(open + 'return {'.length, close).trim()
  const applyMatch = /^apply\(ctx\)\s*\{\s*/u.exec(body)
  if (applyMatch === null) throw new Error('host.js body must open with `apply(ctx) {`')
  body = body.slice(applyMatch[0].length)
  // Strip the closing `},` of the apply method (anchored at the end).
  body = body.replace(/\},\s*$/u, '')
  // Swap sandbox builtins for the real registry API.
  const replaced = body
    .replaceAll('harness.defineTool(', 'defineTool(')
    .replaceAll(/ctx\.effect\(\(\) => harness\.registerTool\(ctx, ([A-Za-z_$][\w$]*)\)\)/gu, 'ctx.tools.register($1)')
  if (replaced.includes('harness.')) {
    throw new Error(`host.js still references harness builtins: ${[...replaced.matchAll(/harness\.[A-Za-z]+/g)].map((m) => m[0]).join(', ')}`)
  }
  return replaced
}

function buildIndex(pluginId, body, registersTools) {
  const lines = [
    `// ${pluginId} — packaged form of plugins/${pluginId}/host.js.`,
    '// ESM module exporting the Cordis function-plugin contract the loader',
    '// expects: named `name` / `inject` / `apply` exports, no default export.',
    `// Generated by scripts/package-plugins.mjs from the dynamic host.js source.`,
    'import { defineTool } from \'@deepseek-ai/dsh-tools\'',
    '',
    `export const name = '${pluginId}'`,
    ...(registersTools ? [`export const inject = ['tools']`] : []),
    '',
    'export function apply(ctx) {',
    body,
    '}',
    '',
  ]
  return lines.join('\n')
}

function buildPackageJson(pluginId, meta) {
  return `${JSON.stringify({
    name: `@garder500/harness-plugin-${pluginId}`,
    version: '0.1.0',
    description: meta.desc,
    type: 'module',
    main: 'index.js',
    exports: {
      '.': './index.js',
      './package.json': './package.json',
    },
    license: 'MIT',
    peerDependencies: {
      '@deepseek-ai/cordis': '*',
      '@deepseek-ai/dsh-tools': '*',
    },
  }, null, 2)}\n`
}

const requested = process.argv.slice(2)
const ids = requested.length > 0 ? requested : Object.keys(PLUGIN_META)

for (const id of ids) {
  const meta = PLUGIN_META[id]
  if (meta === undefined) throw new Error(`unknown plugin id: ${id}`)
  const dir = join(pluginsDir, id)
  const hostPath = join(dir, 'host.js')
  const source = await readFile(hostPath, 'utf8')
  const body = convertHostSource(source)
  const registersTools = body.includes('ctx.tools.register(') || /defineTool\(/u.test(body)
  const index = buildIndex(id, body, registersTools)
  await writeFile(join(dir, 'index.js'), index)
  await writeFile(join(dir, 'package.json'), buildPackageJson(id, meta))
  console.log(`packaged ${id} (${index.split('\n').length} lines, inject=${registersTools ? 'tools' : 'none'})`)
}
console.log('done')
