// grep_search — packaged form of plugins/grep_search/host.js.
// ESM module exporting the Cordis function-plugin contract the loader
// expects: named `name` / `inject` / `apply` exports, no default export.
// Generated by scripts/package-plugins.mjs from the dynamic host.js source.
import { defineTool } from '@deepseek-ai/dsh-tools'

export const name = 'grep_search'
export const inject = ['tools']

export function apply(ctx) {
const DEFAULT_CONTEXT = 2
    const MAX_CONTEXT = 10
    const MAX_MATCHES = 100
    const MAX_RENDERED_LINES = 250

    function render(value) {
      const head = `${value.path} — ${value.matchCount} match${value.matchCount === 1 ? '' : 'es'} for /${value.pattern}/`
      if (value.lines.length === 0) return `${head}\n(no matches)`
      const body = value.lines
        .map((line) => `${line.isMatch ? '>' : ' '} ${String(line.lineNumber).padStart(5)} | ${line.text}`)
        .join('\n')
      const tail = value.truncated ? `\n(${value.truncated} further matches omitted — narrow the pattern)` : ''
      return `${head}\n\n${body}${tail}`
    }

    const tool = defineTool({
      name: 'grep_search',
      description: 'Search a single target file with a regular expression and return ONLY the matching lines plus their adjacent context lines. Prefer this over ingesting a whole file: find where the pattern occurs, then read the exact slice with chunk_reader.',
      parameters: {
        target_file: { type: 'string', required: true, description: 'Path of the file to search; relative paths resolve against the session workspace.' },
        regex_pattern: { type: 'string', required: true, description: 'JavaScript regular expression pattern (no flags; matched per line).' },
        context_lines: { type: 'number', description: `Adjacent lines to include around each match (default ${DEFAULT_CONTEXT}, max ${MAX_CONTEXT}).` },
      },
      output: {
        schema: {
          type: 'object',
          additionalProperties: false,
          properties: {
            path: { type: 'string', required: true },
            pattern: { type: 'string', required: true },
            matchCount: { type: 'integer', required: true },
            lines: {
              type: 'array',
              items: {
                type: 'object',
                additionalProperties: false,
                properties: {
                  lineNumber: { type: 'integer', required: true },
                  text: { type: 'string', required: true },
                  isMatch: { type: 'boolean', required: true },
                },
              },
            },
            truncated: { type: 'integer' },
          },
        },
        render: (_args, value) => [{ type: 'text', text: render(value) }],
      },
      isConcurrencySafe: () => true,
      async execute(args, exec) {
        const fs = ctx.get('fs')
        if (fs === undefined) throw new Error('grep_search: filesystem service unavailable')
        const cwd = exec.agent?.session.header.cwd
        const target = await fs.resolve(args.target_file, {
          ...(cwd !== undefined ? { cwd } : {}),
          signal: exec.signal,
        })
        const info = await fs.stat(target, exec.signal)
        if (info === undefined) throw new Error(`grep_search: "${target.displayPath}" not found`)
        if (info.type !== 'file') throw new Error(`grep_search: "${target.displayPath}" is not a regular file`)

        let re
        try {
          re = new RegExp(args.regex_pattern)
        } catch (error) {
          throw new Error(`grep_search: invalid regex_pattern: ${error instanceof Error ? error.message : String(error)}`)
        }

        const text = await fs.readText(target, exec.signal)
        const lines = text.split(/\r?\n/)
        const context = Math.min(Math.max(0, Math.floor(args.context_lines ?? DEFAULT_CONTEXT)), MAX_CONTEXT)

        // Collect match line indices (0-based), bounded.
        const matchIndexes = []
        for (let i = 0; i < lines.length; i++) {
          if (matchIndexes.length >= MAX_MATCHES) break
          re.lastIndex = 0 // a user-supplied /g pattern must stay stateless per line
          if (re.test(lines[i])) matchIndexes.push(i)
        }

        // Build the set of rendered line numbers: each match + its context.
        const wanted = new Set()
        for (const m of matchIndexes) {
          const start = Math.max(0, m - context)
          const end = Math.min(lines.length - 1, m + context)
          for (let i = start; i <= end; i++) wanted.add(i)
        }

        const rendered = []
        for (const i of wanted) {
          if (rendered.length >= MAX_RENDERED_LINES) break
          rendered.push({ lineNumber: i + 1, text: lines[i], isMatch: matchIndexes.includes(i) })
        }

        const omitted = matchIndexes.length - rendered.filter((line) => line.isMatch).length
        return {
          path: target.displayPath,
          pattern: args.regex_pattern,
          matchCount: matchIndexes.length,
          lines: rendered,
          ...(omitted > 0 ? { truncated: omitted } : {}),
        }
      },
    })

    ctx.tools.register(tool)
  
}
